### ISSUE TITLE
Modernize and clean up this repo

### ISSUE THREAD

**Issue by EyePulp** [mirusresearch/tiptap-editor#29]
## 🎩 Feature Request

The repo is a bit crufty and could use some house-cleaning.

### Expected behavior

We need to bring this project up to modern js package standards.

- [ ] This will become v2.0 
- [x] Convert to current version of [tiptap](https://tiptap.dev/) 2.x
- [x] Convert to `vite` for dev & building
- [x] Write `vitest` unit tests to cover mirus specific features (preferably using jest-style tests)
- [ ] Setup Github actions for build & npm publishing of new versions
- [x] Update the README accordingly

Stretch Goals
- [ ] Make it Vue 2 & Vue 3 compatible

**Comment by jeremygarey** [comment]
The editor is running on tiptap 2.0.0 on this branch: https://github.com/mirusresearch/tiptap-editor/tree/29-modernize-repo

Bold, italics, unordered lists, placeholders, and the character count all work. Our custom `Warnings` extension will still need to be redone to get warnings up and running on tiptap version 2.
